default_stages: [pre-commit]
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: jsonschema/api-docs.md
      - id: detect-private-key
  - repo: https://github.com/google/yamlfmt
    rev: v0.12.1
    hooks:
      - id: yamlfmt
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.7
    hooks:
      - id: typos
