receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - "*"
processors:
  batch:
exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp]
