global:
  scrape_interval: 15s
  external_labels:
    monitor: 'monitoring'
rule_files:
  - 'alerts/*.rules'
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - 'alertmanager:9093'
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:17608
          - host.docker.internal:17608
          - host.docker.internal:2112
          - host.docker.internal:9187
  - job_name: kafka-exporter
    static_configs:
      - targets: ['kafka-exporter:10000']
        labels:
          container: 'kafka-exporter'
  - job_name: postgres-exporter
    static_configs:
      - targets: ["host.docker.internal:9187"]
