route:
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: alerts

receivers:
  - name: alerts
    slack_configs:
      - send_resolved: true
        text: "{{ .CommonAnnotations.description }}"
        channel: alerts-sink
        api_url: http://localhost:17608/metrics
