#!/bin/bash
set -euo pipefail

# KEYS NEED TO BE PLACED IN HERE FROM THE DECRYPTED FILE
export GITHUB_TOKEN="xxx"

export SONAR_TOKEN="yyy"

export SECRET_GHCR_PUBLISH_TOKEN="ggg"

export SECRET_GCR_PUBLISH_TOKEN="zzz"

export ATLAS_CLOUD_TOKEN="aaa"

export APOLLO_KEY="bbb"

export TURSO_TOKEN="ttt"